id: P003076
initial_creation_type: ocr
source_metadata:
  id: bdr:W23724
  title: གསུང་ངག་རིན་པོ་ཆེ་ལམ་འབྲས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཀུན་འདུས་མེ་ལོང
  author: ''
  volumes:
    3aeda4e908994644a48c75c2669816e9:
      image_group_id: I4199
      title: ''
      volume_number: 1
      total_pages: 356
