id: I00F40526
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T00:10:11+00:00'
last_modified: '2022-06-07T17:24:08.411477+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23724
  title: གསུང་ངག་རིན་པོ་ཆེ་ལམ་འབྲས་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་ཀུན་འདུས་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '7332':
      image_group_id: I4199
      title: ''
      total_pages: 356
      order: 1
      base_file: 7332.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
